# Generated by Django 5.0.4 on 2024-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(db_index=True, max_length=3, verbose_name='Код страны валюты')),
                ('date', models.DateField(db_index=True, verbose_name='Дата курса валюты')),
                ('rate', models.FloatField(verbose_name='Курс валюты')),
            ],
            options={
                'verbose_name': 'Курс обмена валюты',
                'verbose_name_plural': 'Курсы обмена валют',
            },
        ),
    ]
