# Generated by Django 5.0.4 on 2024-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('charcode', 'date'), name='unique_charcode_date'),
        ),
    ]
